# Generated by Django 4.2.7 on 2026-03-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='应用名称')),
                ('description', models.TextField(blank=True, verbose_name='应用描述')),
                ('version', models.CharField(default='1.0.0', max_length=50, verbose_name='版本号')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('deploying', '部署中'), ('error', '异常')], default='stopped', max_length=20, verbose_name='状态')),
                ('repo_url', models.CharField(blank=True, max_length=255, verbose_name='仓库地址')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用列表',
                'db_table': 'app_info',
            },
        ),
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('role_type', models.CharField(choices=[('developer', '开发人员'), ('tester', '测试人员'), ('ops', '运维人员')], max_length=20, verbose_name='角色类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色列表',
                'db_table': 'role_info',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('user', '普通用户')], default='user', max_length=20, verbose_name='角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户列表',
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('can_create', models.BooleanField(default=False, verbose_name='新增权限')),
                ('can_read', models.BooleanField(default=True, verbose_name='查询权限')),
                ('can_update', models.BooleanField(default=False, verbose_name='修改权限')),
                ('can_delete', models.BooleanField(default=False, verbose_name='删除权限')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.appinfo', verbose_name='应用（为空表示所有应用）')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.roleinfo', verbose_name='角色')),
            ],
            options={
                'verbose_name': '应用权限',
                'verbose_name_plural': '应用权限列表',
                'db_table': 'app_permission',
                'unique_together': {('role', 'app')},
            },
        ),
    ]
